version = 0.1

[default.deploy.parameters]
stack_name = "tarot-app"
resolve_s3 = true
s3_prefix = "tarot-app"
region = "us-west-2"
profile = "engines2k"
capabilities = "CAPABILITY_IAM"
image_repositories = []
