name: Build and deploy as S3 static site
run-name: ${{ github.actor }} is deploying Aptarot 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]
env:
  APP_LOCATION: "/"
  APP_ARTIFACT_LOCATION: "build"
  BUCKET_NAME: "tarot-app-022365389144-us-west-2"
  DISTRIBUTION_ID: "E1K4R45A074P8"
jobs:
  Deploy-S3-Bucket:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8 # or your preferred version
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # or your preferred version
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Build and deploy to S3
      run: |
        pnpm build
        aws s3 sync ./build s3://${{ env.BUCKET_NAME }} --delete
        aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths '/*'
